version: 2

sources:
  - name: biblioteca
    database: postgres
    schema: public
    tables:
      - name: libros_fisicos
        description: "Información sobre los libros físicos disponibles en la biblioteca."
      - name: prestamos
        description: "Registros de préstamos de libros."
      - name: ejemplares
        description: "Detalles de los ejemplares de libros."
      - name: libros
        description: "Información general de los libros."
      - name: usuarios
        description: "Detalles de los usuarios de la biblioteca."
      - name: reservas
        description: "Registros de reservas de libros."

models:
  - name: copias_disponibles
    description: "Modelo que proporciona datos sobre las copias disponibles en la biblioteca."
    columns:
      - name: isbn
        description: "isbn del libro."
        data_tests:
          - unique
          - not_null
          - relationships:
              to: ref('libros_fisicos')
              field: isbn
      - name: copias_disponibles
        description: "Número de copias disponibles del libro."
        data_tests:
          - not_null
    sources:
      - name: biblioteca
        tables:
          - name: libros_fisicos
    refs:
      - name: libros_prestados

  - name: deudores
    description: "Modelo que proporciona datos sobre los deudores de la biblioteca."
    columns:
      - name: dni
        description: "Identificador único del usuario."
        data_tests:
          - not_null
          - relationships:
              to: ref('usuarios')
              field: dni
      - name: libro_prestado
        description: "Título del libro prestado."
        data_tests:
          - not_null
          - relationships:
              to: ref('libros_fisicos')
              field: titulo
      - name: correo_usuario
        description: "Correo electrónico del usuario."
        data_tests:
          - not_null
          - relationships:
              to: ref('usuarios')
              field: email
      - name: dias_deuda
        description: "Cantidad de días de deuda."
        data_tests:
          - not_null
          
    sources:
      - name: biblioteca
        tables:
          - name: prestamos
          - name: ejemplares
          - name: libros_fisicos
          - name: libros
          - name: usuarios

  - name: libros_prestados
    description: "Modelo que proporciona datos sobre los libros prestados."
    columns:
      - name: isbn
        description: "isbn del libro."
        data_tests:
          - unique
          - not_null
          - relationships:
              to: ref('libros_fisicos')
              field: isbn
      - name: cantidad_prestamos
        description: "Número de veces que el libro ha sido prestado."
        data_tests:
          - not_null
    sources:
      - name: biblioteca
        tables:
          - name: prestamos
          - name : ejemplares

  - name: reservas_activas
    description: "Modelo que proporciona datos sobre las reservas activas de libros."
    columns:
      - name: isbn
        description: "isbn del libro reservado."
        data_tests:
          - unique
          - not_null
          - relationships:
              to: ref('libros_fisicos')
              field: isbn
      - name: cantidad_reservas
        description: "Número de reservas activas del libro."
        data_tests:
          - not_null
    sources:
      - name: biblioteca
        tables:
          - name: reservas

  - name: reservas_insatisfechas
    description: "Modelo que proporciona datos sobre las reservas insatisfechas."
    columns:
      - name: isbn
        description: "isbn del libro solicitado."
        data_tests:
          - unique
          - not_null
          - relationships:
              to: ref('libros_fisicos')
              field: isbn
      - name: cant_reservas_insatisfechas
        description: "Cantidad de reservas insatisfechas del libro."
        data_tests:
          - not_null

    refs:
      - name: reservas_activas
      - name: copias_disponibles
